openapi: 3.2.0
info:
  title: Subscriber Engine subscriber_engine Subscriber API
  version: 1.0.0
security:
- TokenHeader: []
tags:
- name: subscriber_engine Subscriber
paths:
  /subscriber_engine/api/v1/sources/subscriber_lists/:
    get:
      summary: Subscriber sources endpoint
      description: Returns current active signups
      tags:
      - subscriber_engine Subscriber
      responses:
        '200':
          description: Available signup flows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriberSource'
      operationId: getSubscriberEngineApiV1SourcesSubscriberLists
      x-operation-id-source: derived
components:
  schemas:
    SubscriberSource:
      type: object
      properties:
        subscribe_identifier:
          type: string
        name:
          type: string
  securitySchemes:
    TokenHeader:
      type: apiKey
      in: header
      name: Authorization
