openapi: 3.2.0
info:
  license:
    name: Private
  title: Sensus Webhooks API
  version: 0.1.0
servers:
- url: /sensus-webhook
tags:
- name: Sensus Webhooks
paths:
  /:
    get:
      description: Says 'Hello, Emotive!'
      operationId: controllers.base.home
      responses:
        '200':
          content:
            text/html:
              schema:
                type: string
          description: The string 'Hello, Emotive!'
      summary: Hello, Emotive!
      tags:
      - Sensus Webhooks
