openapi: 3.2.0
info:
  license:
    name: Private
  title: Emotive Auth Server Admin API
  version: 0.1.0
servers:
- url: /auth
tags:
- name: Admin
paths:
  /v1/admin/token:
    get:
      operationId: controllers.resource.admin_token
      responses:
        '302':
          description: Emotive admin home page.
          headers:
            Location:
              description: Emotive admin home page.
              schema:
                format: uri
                type: string
      summary: Sets Admin JWT cookie and redirects to Admin homepage
      tags:
      - Admin
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
      x-apikeyInfoFunc: core.api_security.api_key
